export class Tender {
    constructor(
        public title: string = 'N/A',
        public description: string = 'N/A',
        public published_on: string = 'N/A',
        public awarded_on: string = 'N/A',
        public submission_date: string = 'N/A',
        public deadline_date: string = 'N/A',
        public cancelled_on: string = 'N/A',
        public currency_name: string = 'N/A',
        public organization_name: string = 'N/A',
        public status: string = 'N/A',
        public country: any = null,
        public estimated_low_value: string = 'N/A',
        public estimated_high_value: string = 'N/A',
        public estimated_value: string = 'N/A',
        public average_score: string = 'N/A',
        public collaboration: string = 'N/A',
        public user_status: string = 'N/A',
        public favourite: string = 'N/A',
        public keywords: Array<any> = [],
        public created_at: string = 'N/A',
        public updated_at: string = 'N/A',
        public award_published_on: string = 'N/A',
        public potential_retender_date: string = 'N/A',
        public tender_urls: string = 'N/A',
        public award_urls: string = 'N/A',
        public contact_email: string = 'N/A',
        public contact_phone: string = 'N/A',
        public gsins: Array<any> = [],
        public unspsces: Array<any> = [],
        public cpvs: Array<any> = [],
        public naicses: Array<any> = [],
        public ngips: Array<any> = []
    ) { }
}
